apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
spec:
  {{- with .Values.deployment.labels }} 
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.ports }} 
  ports:         
    {{- toYaml . | nindent 4 }}
  {{- end }}
  type: {{ .Values.service.type }}